CREATE TABLE ID_SEQ_TABLE (
    VALUUE BIGINT
);

CREATE TABLE BAND (
    ID BIGINT PRIMARY KEY,
    NAME VARCHAR(20),
    ESTABLISHMENT_DATE DATE
);

CREATE TABLE ARTIST (
    ID BIGINT PRIMARY KEY,
    NAME VARCHAR(20),
    AGE INT,
    INSTRUMENT VARCHAR(20)
);

CREATE TABLE BAND_ARTIST (
    ID BIGINT PRIMARY KEY,
    ARTIST_ID BIGINT CONSTRAINT FK_BA_ARTIST REFERENCES ARTIST,
    BAND_ID BIGINT CONSTRAINT FK_BA_BAND REFERENCES BAND
);

INSERT INTO ID_SEQ_TABLE VALUES (10);

INSERT INTO BAND VALUES
(1, 'Wintersun', '2003-01-01');

INSERT INTO ARTIST VALUES
(1, 'Jari Mäenpää', 39, 'Vocal'),
(2, 'Teemu Mäntysaari', 30, 'Guitar');

INSERT INTO BAND_ARTIST VALUES
(1, 1, 1),
(2, 2, 1);